sonar.projectKey=link-it_govpay-console
sonar.organization=link-it

sonar.sources=projects/govpay-console/src
sonar.tests=projects/govpay-console/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
