/*
 * GovPay - Porta di Accesso al Nodo dei Pagamenti SPC
 * http://www.gov4j.it/govpay
 *
 * Copyright (c) 2014-2026 Link.it srl (http://www.link.it).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 */

import {
  bootstrapHouseDoor,
  bootstrapReceipt,
  bootstrapCreditCard2Front,
  bootstrapBank,
  bootstrapArchive,
  bootstrapList,
  bootstrapPerson,
  bootstrapPersonLock,
  bootstrapBuilding,
  bootstrapGear,
  bootstrapClockHistory,
  bootstrapFolder,
  bootstrapBoxArrowRight,
  bootstrapBoxArrowInRight,
  bootstrapFileEarmarkText,
  bootstrapShieldCheck,
  bootstrapCollection,
  bootstrapGrid3x3Gap,
  bootstrapHouse,
  bootstrapCart3,
  bootstrapPlus,
  bootstrapSearch,
  bootstrapDownload,
  bootstrapChevronRight,
  bootstrapChevronLeft,
  bootstrapChevronDown,
  bootstrapChevronUp,
  bootstrapArrowUpShort,
  bootstrapXLg,
  bootstrapX,
  bootstrapCheck2,
  bootstrapCheckCircle,
  bootstrapXCircle,
  bootstrapExclamationTriangle,
  bootstrapInfoCircle,
  bootstrapThreeDotsVertical,
  bootstrapSun,
  bootstrapMoon,
  bootstrapCircleHalf,
  bootstrapGlobe,
  bootstrapSliders2,
  bootstrapQuestionCircle,
  bootstrapBookHalf,
  bootstrapLifePreserver,
  bootstrapInboxes,
  bootstrapPersonExclamation,
} from '@ng-icons/bootstrap-icons';

/**
 * Set di icone Bootstrap registrato globalmente in `app.config.ts`.
 * Le voci sidebar referenziano i nomi qui per chiave.
 */
export const APP_ICONS = {
  bootstrapHouseDoor,
  bootstrapHouse,
  bootstrapReceipt,
  bootstrapCreditCard2Front,
  bootstrapBank,
  bootstrapArchive,
  bootstrapList,
  bootstrapPerson,
  bootstrapPersonLock,
  bootstrapBuilding,
  bootstrapGear,
  bootstrapClockHistory,
  bootstrapFolder,
  bootstrapBoxArrowRight,
  bootstrapBoxArrowInRight,
  bootstrapFileEarmarkText,
  bootstrapShieldCheck,
  bootstrapCollection,
  bootstrapGrid3x3Gap,
  bootstrapCart3,
  bootstrapPlus,
  bootstrapSearch,
  bootstrapDownload,
  bootstrapChevronRight,
  bootstrapChevronLeft,
  bootstrapChevronDown,
  bootstrapChevronUp,
  bootstrapArrowUpShort,
  bootstrapXLg,
  bootstrapX,
  bootstrapCheck2,
  bootstrapCheckCircle,
  bootstrapXCircle,
  bootstrapExclamationTriangle,
  bootstrapInfoCircle,
  bootstrapThreeDotsVertical,
  bootstrapSun,
  bootstrapMoon,
  bootstrapCircleHalf,
  bootstrapGlobe,
  bootstrapSliders2,
  bootstrapQuestionCircle,
  bootstrapBookHalf,
  bootstrapLifePreserver,
  bootstrapInboxes,
  bootstrapPersonExclamation,
};
